org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# Flutter plugin sources can live on a different drive than this project.
kotlin.incremental=false
MAPBOX_DOWNLOADS_TOKEN=sk.eyJ1IjoibHZ1eHl6IiwiYSI6ImNtOXYxYmlwNjBnc20yanNhbWp5azk0N2gifQ.gqwHDtilw_PixpHH5aMhug
